### ISSUE TITLE
Does not work with new linter

### ISSUE THREAD

**Issue by yuri-karadzhov** [AtomLinter/linter-glsl#57]
An error occurred with new linter 2.1.0
```
[Linter] Invalid Linter Result received
These issues were encountered while processing messages from a linter named 'glsl'
  • Linter Result must be an Array
```

**Comment by Arcanemagus** [comment]
@yuri-karadzhov Note that the only way this could have been triggered is if this package failed to run in some manner, I've got a fix up in #61 that will prevent an invalid response being sent back to Linter, but there is still something wrong that it ever happened in the first place.
