### ISSUE TITLE
Stop using glslangValidator?

### ISSUE THREAD

**Issue by fand** [AtomLinter/linter-glsl#71]
`glslangValidator` makes it difficult to install linter-glsl.
It would be great if we can install linter-glsl without any prerequisites.

As Atom is built on Electron, we can validate GLSL shaders by compiling them background.
Many online GLSL editors have their own validators implemented in this way, such as GLSL Sandbox, Shadertoy, etc.

**Comment by Arcanemagus** [comment]
GLSL Sandbox appears to have a very basic parser ([here](https://github.com/mrdoob/glsl-sandbox/blob/master/static/js/glsl.js)). Shadertoy doesn't seem to publish their source.

So it sounds like you are asking for a completely new linter to be written? This is just a wrapper around `glslangValidator`... the reference validator from the spec itself.

If you find another linter for GLSL code feel free to write a wrapper to bring it into the Atom linter ecosystem, I'd be happy to have it in the organization if you want too 😉.
